name: Metrics
on:
  # Roda todo dia à meia-noite
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente clicando num botão (bom para testar agora)
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token secreto
          token: ${{ secrets.METRICS_TOKEN }}

          # Opções principais
          user: GabrielMazzetti
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Plugin de Linguagens (Mostra Python, R, C++)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_threshold: 0%
          
          # Plugin de Linhas de código (Mostra o volume de trabalho)
          plugin_lines: yes
          
          # Salvar como SVG no seu repo
          filename: github-metrics.svg
